trigger: none
pr: none

pool: 
  name: 'NetCorePublic-Pool'

steps:
# Start by restoring all the dependencies. This needs to be its own task
# from what I can tell. We specifically only target DurableTask.AzureStorage
# and its direct dependencies.
- task: DotNetCoreCLI@2
  displayName: 'Restore nuget dependencies'
  inputs:
    command: restore
    verbosityRestore: Minimal
    projects: 'DurableTask.sln'

# Build the filtered solution in release mode, specifying the continuous integration flag.
- task: VSBuild@1
  displayName: 'Build'
  inputs:
    solution: 'DurableTask.sln'
    vsVersion: 'latest'
    logFileVerbosity: minimal
    configuration: Release
    msbuildArgs: /p:GITHUB_RUN_NUMBER=$(Build.BuildId) /p:ContinuousIntegrationBuild=true